spring:
  application:
    name: asic-service

server:
  port: 8072

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

logging:
  file:
    name: /opt/asicchecker/logs/telegramservice/telegramservice.log
  level:
    root: INFO