spring:
  application:
    name: asic-service
  kafka:
    consumer:
      group-id: telegram-service
      auto-offset-reset: earliest
      bootstrap-servers: "192.168.1.254:9092"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8072

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
    build:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  file:
    name: /opt/asicchecker/logs/telegramservice/telegramservice.log
  level:
    root: INFO

app:
  telegram:
    bot-token: ${TELEGRAM_BOT_TOKEN}
    allowed-chat-id: ${BOT_ALLOWED_CHAT_ID}
