scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: asicservice
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.254:8071']