version: "3.9"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-configs:/etc/grafana
    environment:
      - GF_SERVER_HTTP_PORT=3000
      - TZ=Europe/Moscow
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - default
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prom-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    networks:
      - default
  node-exporter:
    image: prom/node-exporter
    container_name: exporter
    hostname: exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    networks:
      - default
volumes:
  grafana-data:
  grafana-configs:
  prom-data:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16