spring:
  application:
    name: asic-service

server:
  port: 8071

springdoc:
  swagger-ui:
    path: /api.html
    displayRequestDuration: true
    operationsSorter: alpha
    tagsSorter: alpha
  model-converters:
    pageable-converter:
      enabled: true